name: Build FEYKIN AI

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install groq customtkinter pyinstaller

    - name: Inject API Key
      shell: pwsh
      env:
        MY_SECRET_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        # Эта команда заменит заглушку в коде на реальный ключ из Secrets
        (Get-Content ai.py).Replace('PLACEHOLDER_KEY', "$env:MY_SECRET_KEY") | Set-Content ai.py

    - name: Build EXE
      shell: pwsh
      run: |
        $CTK_PATH = python -c "import customtkinter, os; print(os.path.dirname(customtkinter.__file__))"
        python -m PyInstaller --noconfirm --onefile --windowed --add-data "${CTK_PATH};customtkinter/" ai.py

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: FeykinAI
        path: dist/ai.exe
